-- ============================================================
-- Supabase Migration: fmr_projects table
-- Department of Agriculture - RAED Region VI
-- Farm-to-Market Road Development Program (FMRDP) Data
-- Run this SQL in your Supabase SQL Editor
-- ============================================================

-- 1. Create the fmr_projects table (does NOT alter existing projects table)
CREATE TABLE IF NOT EXISTS public.fmr_projects (
  id                    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  year_funded           INTEGER,
  project_name          TEXT NOT NULL,
  location              TEXT DEFAULT '',
  municipality          TEXT DEFAULT '',
  province              TEXT DEFAULT 'Iloilo',
  region                TEXT DEFAULT 'Region VI - Western Visayas',
  target_completion_date TEXT DEFAULT '',
  date_completed        TEXT DEFAULT '',
  status                TEXT NOT NULL DEFAULT 'Proposed',
  remarks               TEXT DEFAULT '',
  accomplishment        INTEGER DEFAULT 0,
  project_length_km     DOUBLE PRECISION DEFAULT 0,
  start_latitude        DOUBLE PRECISION,
  start_longitude       DOUBLE PRECISION,
  end_latitude          DOUBLE PRECISION,
  end_longitude         DOUBLE PRECISION,
  source                TEXT DEFAULT 'DA-RAED Region VI',
  created_at            TIMESTAMPTZ DEFAULT now(),
  updated_at            TIMESTAMPTZ DEFAULT now()
);

-- 2. Enable Row Level Security
ALTER TABLE public.fmr_projects ENABLE ROW LEVEL SECURITY;

-- 3. RLS Policies
CREATE POLICY "Anyone authenticated can view fmr_projects"
  ON public.fmr_projects FOR SELECT TO authenticated USING (true);

CREATE POLICY "Anon users can view fmr_projects"
  ON public.fmr_projects FOR SELECT TO anon USING (true);

CREATE POLICY "Authenticated users can insert fmr_projects"
  ON public.fmr_projects FOR INSERT TO authenticated WITH CHECK (true);

CREATE POLICY "Authenticated users can update fmr_projects"
  ON public.fmr_projects FOR UPDATE TO authenticated USING (true);

CREATE POLICY "Authenticated users can delete fmr_projects"
  ON public.fmr_projects FOR DELETE TO authenticated USING (true);

-- 4. Enable Realtime
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_publication_tables
    WHERE pubname = 'supabase_realtime' AND tablename = 'fmr_projects'
  ) THEN
    ALTER PUBLICATION supabase_realtime ADD TABLE public.fmr_projects;
  END IF;
END $$;

-- ============================================================
-- 5. INSERT DATA: On-Going Projects (2025 Funded)
-- ============================================================

INSERT INTO public.fmr_projects (year_funded, project_name, location, municipality, status, target_completion_date, accomplishment, remarks) VALUES
(2025, 'Concreting of Sitio Hatol to Sitio Katiklan, Brgy. Nanga FMR, Brgy. Nanga, Guimbal, Iloilo', 'Sitio Hatol to Sitio Katiklan, Brgy. Nanga, Guimbal, Iloilo', 'Guimbal', 'On-Going', 'Sept. 26, 2025', 7, '7% Accomplishment'),
(2025, 'Concreting of Brgy. Tabat to Ambarihon FMR, Brgy. Tabat and Brgy. Ambarihon, Tubungan, Iloilo', 'Brgy. Tabat to Ambarihon, Tubungan, Iloilo', 'Tubungan', 'On-Going', 'October 18, 2025', 10, '10% Accomplishment'),
(2025, 'Concreting of Brgy. Bolo FMR, Brgy. Bolo, Maasin, Iloilo', 'Brgy. Bolo, Maasin, Iloilo', 'Maasin', 'On-Going', 'June 16, 2025', 70, '70% Accomplishment'),
(2025, 'Concreting of Brgy. Kinagdan FMR Phase II, Brgy. Kinagdan, Igbaras, Iloilo', 'Brgy. Kinagdan, Igbaras, Iloilo', 'Igbaras', 'On-Going', 'November 14, 2025', 22, '22% Accomplishment'),
(2025, 'Concreting of Brgy. Mambiranan Grande FMR, Brgy. Mambiranan Grande, Passi City, Iloilo', 'Brgy. Mambiranan Grande, Passi City, Iloilo', 'Passi City', 'On-Going', 'July 26, 2025', 31, '31% Accomplishment'),
(2025, 'Concreting of FMR at Brgy. Malapula to Bita-ogan, Sitio Libtog, Passi City, Iloilo', 'Brgy. Malapula & Bita-ogan, Sitio Libtog, Passi City, Iloilo', 'Passi City', 'On-Going', 'August 19, 2025', 45, '45% Accomplishment'),
(2025, 'Construction of Brgy. Sohoton-Brgy. Bagongbong FMR, Barotac Nuevo, Iloilo', 'Brgy. Sohoton & Brgy. Bagongbong, Barotac Nuevo, Iloilo', 'Barotac Nuevo', 'On-Going', 'December 13, 2025', 18, '18% Accomplishment'),
(2025, 'Construction of Brgy. Dalusan-Brgy. Tuy-an West FMR, Maasin, Iloilo', 'Brgy. Tuy-an West FMR, Maasin, Iloilo', 'Maasin', 'On-Going', 'July 26, 2025', 70, '70% Accomplishment'),
(2025, 'Concreting of Brgy. Nueva Union FMR, Brgy. Nueva Union, Passi City, Iloilo', 'Brgy. Nueva Union, Passi City, Iloilo', 'Passi City', 'On-Going', 'August 10, 2025', 47, '47% Accomplishment'),
(2025, 'Road Concreting of Brgy. Cadilang to Brgy. Punong Road Section, Passi City, Iloilo', 'Brgy. Cadilang to Brgy. Punong, Passi City, Iloilo', 'Passi City', 'On-Going', 'July 02, 2025', 56, '56% Accomplishment');

-- ============================================================
-- 6. INSERT DATA: Completed Projects (2024 Funded)
-- ============================================================

INSERT INTO public.fmr_projects (year_funded, project_name, location, municipality, status, date_completed, project_length_km, start_latitude, start_longitude, end_latitude, end_longitude, accomplishment) VALUES
(2024, 'Concreting of Brgy. Alupidian FMR, Brgy. Alupidian, Tigbauan, Iloilo', 'Brgy. Alupidian, Tigbauan, Iloilo', 'Tigbauan', 'Completed', 'January 27, 2025', 0.82, 10.754871, 122.343376, 10.760431, 122.340107, 100),
(2024, 'Concreting of Brgy. Doldol FMR, Brgy. Doldol, San Joaquin, Iloilo', 'Brgy. Doldol, San Joaquin, Iloilo', 'San Joaquin', 'Completed', 'February 04, 2025', 0.67, 10.499249, 122.036870, 10.857924, 122.743392, 100),
(2024, 'Concreting of Brgy. Doldol - Brgy. Languanan FMR, Brgy. Doldol and Brgy. Languanan, San Joaquin, Iloilo', 'Brgy. Doldol and Brgy. Languanan, San Joaquin, Iloilo', 'San Joaquin', 'Completed', 'December 30, 2024', 0.52, 10.513352, 122.049774, 10.509509, 122.049416, 100),
(2024, 'Concreting of Brgy. San Mateo Sur - Brgy. Talagutac FMR, Brgy. San Mateo Sur and Brgy. Talagutac, San Joaquin, Iloilo', 'Brgy. San Mateo Sur and Brgy. Talagutac, San Joaquin, Iloilo', 'San Joaquin', 'Completed', 'March 04, 2025', 0.84, 10.553552, 122.044777, 10.549504, 122.039581, 100),
(2024, 'Concreting of Brgy. Caboloan Norte FMR, Brgy. Caboloan Norte, Oton, Iloilo', 'Brgy. Caboloan Norte, Oton, Iloilo', 'Oton', 'Completed', 'December 05, 2024', 0.90, 10.752419, 122.469620, 10.759667, 122.472228, 100),
(2024, 'Concreting of Brgy. Jamog - Elementary School FMR, Brgy. Jamog, Tigbauan, Iloilo', 'Brgy. Jamog, Tigbauan, Iloilo', 'Tigbauan', 'Completed', 'December 07, 2024', 0.72, 10.755233, 122.355500, 10.857924, 122.352004, 100),
(2024, 'Concreting of Brgy. Qui-anan to Brgy. Dacdacan FMR, Brgy. Qui-anan and Brgy. Dacdacan, San Joaquin, Iloilo', 'Brgy. Qui-anan and Brgy. Dacdacan, San Joaquin, Iloilo', 'San Joaquin', 'Completed', 'March 31, 2025', 1.16, 10.568364, 122.066353, 10.559655, 122.065363, 100),
(2024, 'Concreting of Sitio Victoria, Brgy. Igcocolo to Sitio Igtuba, Brgy. Camangahan FMR, Brgy. Igcocolo and Brgy. Camangahan, Guimbal, Iloilo', 'Brgy. Igcocolo and Brgy. Camangahan, Guimbal, Iloilo', 'Guimbal', 'Completed', 'February 07, 2025', 0.77, 10.711030, 122.325300, 10.710363, 122.318840, 100),
(2024, 'Concreting of Brgy. Balud FMR, Brgy. Balud, Dumangas, Iloilo', 'Brgy. Balud, Dumangas, Iloilo', 'Dumangas', 'Completed', 'November 13, 2024', 0.77, 10.829432, 122.642872, 10.825251, 122.648391, 100),
(2024, 'Concreting of Sitio Sapa, Brgy. Tamboilan FMR, Brgy. Tamboilan, Dumangas, Iloilo', 'Brgy. Tamboilan, Dumangas, Iloilo', 'Dumangas', 'Completed', 'December 27, 2024', 0.73, 10.851519, 122.734154, 10.854319, 122.740017, 100),
(2024, 'Concreting of Sitio Riverside, Brgy. Capaliz to Brgy. Cali FMR, Brgy. Capaliz and Brgy. Cali, Dumangas, Iloilo', 'Brgy. Capaliz and Brgy. Cali, Dumangas, Iloilo', 'Dumangas', 'Completed', 'December 12, 2024', 0.62, 10.842207, 122.702983, 10.840060, 122.707972, 100),
(2024, 'Concreting of Sitio Liboo, Brgy. Calao FMR, Brgy. Calao, Dumangas, Iloilo', 'Brgy. Calao, Dumangas, Iloilo', 'Dumangas', 'Completed', 'July 11, 2024', 0.73, 10.864048, 122.702286, 10.862173, 122.707230, 100),
(2024, 'Concreting of Brgy. Sapao FMR, Brgy. Sapao, Dumangas, Iloilo', 'Brgy. Sapao, Dumangas, Iloilo', 'Dumangas', 'Completed', 'November 01, 2024', 0.17, 10.780561, 122.709199, 10.857924, 122.743392, 100),
(2024, 'Concreting of Sitio Proper, Brgy. Paloc Sool FMR, Brgy. Paloc Sool, Dumangas, Iloilo', 'Brgy. Paloc Sool, Dumangas, Iloilo', 'Dumangas', 'Completed', 'July 11, 2024', 0.77, 10.835936, 122.736234, 10.837542, 122.741755, 100),
(2024, 'Concreting of Paloc Bigque FMR, Brgy. Paloc Bigque, Dumangas, Iloilo', 'Brgy. Paloc Bigque, Dumangas, Iloilo', 'Dumangas', 'Completed', 'November 27, 2024', 0.33, 10.842419, 122.727154, 10.845090, 122.725880, 100),
(2024, 'Concreting of Sitio Tacas, Brgy. Barasan FMR, Brgy. Barasan, Dumangas, Iloilo', 'Brgy. Barasan, Dumangas, Iloilo', 'Dumangas', 'Completed', 'September 16, 2024', 0.34, 10.869863, 122.736030, 10.872449, 122.735751, 100),
(2024, 'Concreting of Purok 1, Brgy. Nanding Lopez FMR, Brgy. Nanding Lopez, Dumangas, Iloilo', 'Brgy. Nanding Lopez, Dumangas, Iloilo', 'Dumangas', 'Completed', 'September 11, 2024', 0.38, 10.875744, 122.754584, 10.877523, 122.751765, 100),
(2024, 'Concreting of Brgy. Cahaguikican FMR, Brgy. Cahaguikican, Pototan, Iloilo', 'Brgy. Cahaguikican, Pototan, Iloilo', 'Pototan', 'Completed', 'November 08, 2024', 0.82, 10.908634, 122.621433, 10.905831, 122.627587, 100),
(2024, 'Concreting of Brgy. Igang FMR, Brgy. Igang, Pototan, Iloilo', 'Brgy. Igang, Pototan, Iloilo', 'Pototan', 'Completed', 'November 12, 2024', 0.80, 10.912879, 122.631879, 10.908710, 122.637146, 100),
(2024, 'Concreting of Burak FMR, Brgy. Burak, Maasin, Iloilo', 'Brgy. Burak, Maasin, Iloilo', 'Maasin', 'Completed', 'September 05, 2024', 0.31, 10.942039, 122.459245, 10.943760, 122.457929, 100),
(2024, 'Concreting of Brgy. Barasan FMR, Brgy. Barasan, Pototan, Iloilo', 'Brgy. Barasan, Pototan, Iloilo', 'Pototan', 'Completed', 'September 16, 2024', 0.98, 10.955754, 122.650389, 10.919785, 122.654228, 100),
(2024, 'Concreting of Brgy. San Juan Crisostomo FMR, Brgy. San Juan Crisostomo, Anilao, Iloilo', 'Brgy. San Juan Crisostomo, Anilao, Iloilo', 'Anilao', 'Completed', 'August 12, 2024', 1.03, 10.861994, 122.703520, 10.961550, 122.705282, 100),
(2024, 'Concreting of Brgy. Romblon FMR, Brgy. Romblon, Duenas, Iloilo', 'Brgy. Romblon, Duenas, Iloilo', 'Duenas', 'Completed', 'September 16, 2024', 0.81, 11.031092, 122.568348, 11.035866, 122.743392, 100),
(2024, 'Concreting of Brgy. Juanico FMR, Brgy. Juanico, Banate, Iloilo', 'Brgy. Juanico, Banate, Iloilo', 'Banate', 'Completed', 'January 03, 2025', 0.71, 11.086841, 122.781041, 11.086690, 122.774887, 100),
(2024, 'Concreting of Sitio Patahan, Brgy. Cansilayan FMR, Brgy. Cansilayan, Dumangas, Iloilo', 'Brgy. Cansilayan, Dumangas, Iloilo', 'Dumangas', 'Completed', 'July 11, 2024', 0.69, 10.850530, 122.695127, 10.849480, 122.690014, 100),
(2024, 'Concreting of Brgy. Pagdugue FMR, Brgy. Pagdugue, Dumangas, Iloilo', 'Brgy. Pagdugue, Dumangas, Iloilo', 'Dumangas', 'Completed', 'October 18, 2024', 0.82, 10.853790, 122.669596, 10.858098, 122.664047, 100),
(2024, 'Concreting of Brgy. Ilaya 2nd to Brgy. Ilaya 3rd FMR, Brgy. Ilaya 2nd and Brgy. Ilaya 3rd, Dumangas, Iloilo', 'Brgy. Ilaya 2nd and Brgy. Ilaya 3rd, Dumangas, Iloilo', 'Dumangas', 'Completed', 'September 16, 2024', 0.70, 10.831772, 122.714825, 10.838124, 122.715308, 100),
(2024, 'Concreting of Brgy. Tuburan FMR, Brgy. Tuburan, Lambunao, Iloilo', 'Brgy. Tuburan, Lambunao, Iloilo', 'Lambunao', 'Completed', 'September 16, 2024', 1.17, 11.038582, 122.535801, 11.039665, 122.545000, 100),
(2024, 'Concreting of Brgy. Dongsol FMR, Brgy. Dongsol, Pototan, Iloilo', 'Brgy. Dongsol, Pototan, Iloilo', 'Pototan', 'Completed', 'October 29, 2024', 0.70, 10.862732, 122.640184, 10.867913, 122.638847, 100),
(2024, 'Concreting of Brgy. Tigbauan Road FMR, Brgy. Tigbauan Road, Cabatuan, Iloilo', 'Brgy. Tigbauan Road, Cabatuan, Iloilo', 'Cabatuan', 'Completed', 'October 08, 2024', 0.86, 10.916070, 122.485879, 10.915162, 122.479850, 100),
(2024, 'Concreting of Brgy. Crespo FMR, Brgy. Crespo, Sara, Iloilo', 'Brgy. Crespo, Sara, Iloilo', 'Sara', 'Completed', 'October 16, 2024', 0.45, 11.249356, 123.046413, 11.252294, 123.051381, 100),
(2024, 'Concreting of Sitio Tuburan, Brgy. Pasig FMR, Brgy. Pasig, Sara, Iloilo', 'Brgy. Pasig, Sara, Iloilo', 'Sara', 'Completed', 'January 16, 2025', 0.66, 11.270422, 123.012791, 11.269780, 123.005527, 100),
(2024, 'Concreting of Brgy. Tabu-an FMR, Brgy. Tabu-an, Estancia, Iloilo', 'Brgy. Tabu-an, Estancia, Iloilo', 'Estancia', 'Completed', 'December 07, 2024', 0.56, 11.459146, 123.117412, 11.456367, 123.118675, 100),
(2024, 'Concreting of Brgy. Madanlog FMR, Brgy. Madanlog, San Dionisio, Iloilo', 'Brgy. Madanlog, San Dionisio, Iloilo', 'San Dionisio', 'Completed', 'July 16, 2024', 0.38, 11.375135, 123.112541, 11.377215, 123.115022, 100),
(2024, 'Concreting of Brgy. Nueva Invencion FMR, Brgy. Nueva Invencion, Barotac Viejo, Iloilo', 'Brgy. Nueva Invencion, Barotac Viejo, Iloilo', 'Barotac Viejo', 'Completed', 'December 07, 2024', 0.51, 11.115920, 122.886096, 11.121172, 122.882904, 100),
(2024, 'Concreting of Brgy. Pagsanga-an to Brgy. Tigum FMR, Brgy. Pagsanga-an and Brgy. Tigum, Pavia, Iloilo', 'Brgy. Pagsanga-an and Brgy. Tigum, Pavia, Iloilo', 'Pavia', 'Completed', 'October 30, 2024', 0.76, 10.775358, 122.562341, 10.781531, 122.561119, 100),
(2024, 'Concreting of Brgy. Ulay Bugang FMR, Brgy. Ulay Bugang, Alimodian, Iloilo', 'Brgy. Ulay Bugang, Alimodian, Iloilo', 'Alimodian', 'Completed', 'March 24, 2025', 0.70, 10.800730, 122.421371, 10.801757, 122.416529, 100),
(2024, 'Concreting of Brgy. Camando to Brgy. Paoy FMR, Brgy. Camando and Brgy. Paoy, Leon, Iloilo', 'Brgy. Camando and Brgy. Paoy, Leon, Iloilo', 'Leon', 'Completed', 'October 29, 2024', 0.55, 10.861994, 122.382478, 10.808584, 122.381051, 100),
(2024, 'Concreting of Brgy. Bulod FMR, Brgy. Bulod, Alimodian, Iloilo', 'Brgy. Bulod, Alimodian, Iloilo', 'Alimodian', 'Completed', 'November 19, 2024', 0.80, 10.835464, 122.439194, 10.828766, 122.439165, 100),
(2024, 'Concreting of Brgy. Malublub, Leon to Brgy. Abang-abang, Alimodian FMR, Brgy. Malublub, Leon and Abang-abang, Alimodian, Iloilo', 'Brgy. Malublub, Leon and Abang-abang, Alimodian, Iloilo', 'Leon', 'Completed', 'May 22, 2025', 2.15, 10.840196, 122.367625, 10.856758, 122.367802, 100);

-- ============================================================
-- 7. INSERT DATA: Proposed Projects
-- ============================================================

INSERT INTO public.fmr_projects (project_name, location, municipality, status, accomplishment) VALUES
('Concreting of Sitio Sapa Bato, Brgy. Nalundan FMR, Brgy. Nalundan, Guimbal, Iloilo', 'Brgy. Nalundan, Guimbal, Iloilo', 'Guimbal', 'Proposed', 0),
('Concreting of Brgy. Bagay FMR, Brgy. Bagay, Igbaras, Iloilo', 'Brgy. Bagay, Igbaras, Iloilo', 'Igbaras', 'Proposed', 0),
('Opening/Construction of Brgy. Escalantera FMR, Brgy. Escalantera, San Joaquin, Iloilo (Phase 2)', 'Brgy. Escalantera, San Joaquin, Iloilo', 'San Joaquin', 'Proposed', 0),
('Concreting of Brgy. Mayang - Brgy. Talento FMR, Tubungan, Iloilo', 'Brgy. Mayang - Brgy. Talento, Tubungan, Iloilo', 'Tubungan', 'Proposed', 0),
('Concreting of Brgy. Cansilayan FMR, Brgy. Cansilayan, Tigbauan, Iloilo', 'Brgy. Cansilayan, Tigbauan, Iloilo', 'Tigbauan', 'Proposed', 0),
('Concreting of Brgy. Trapiche to Brgy. Galang to Brgy. Salngan FMR, Oton, Iloilo', 'Brgy. Trapiche, Brgy. Galang and Brgy. Salngan, Oton, Iloilo', 'Oton', 'Proposed', 0),
('Concreting of Brgy. Lubacan to Brgy. Sipitan-Badiang FMR, Guimbal, Iloilo', 'Brgy. Lubacan and Brgy. Sipitan-Badiang, Guimbal, Iloilo', 'Guimbal', 'Proposed', 0),
('Concreting of Sitio Durog, Brgy. Camangahan FMR, Brgy. Camangahan, Guimbal, Iloilo', 'Brgy. Camangahan, Guimbal, Iloilo', 'Guimbal', 'Proposed', 0),
('Concreting of Proper to Sitio Bacong, Brgy. Catiringan FMR, Brgy. Catiringan, Igbaras, Iloilo', 'Brgy. Catiringan, Igbaras, Iloilo', 'Igbaras', 'Proposed', 0),
('Concreting of Brgy. Talayatay to Brgy. Buenavista FMR, Igbaras, Iloilo', 'Brgy. Talayatay & Brgy. Buenavista, Igbaras, Iloilo', 'Igbaras', 'Proposed', 0),
('Concreting of Brgy. Balibagan Oeste FMR, Brgy. Balibagan Oeste, Sta. Barbara, Iloilo', 'Brgy. Balibagan Oeste, Sta. Barbara, Iloilo', 'Sta. Barbara', 'Proposed', 0),
('Construction of Brgy. Isian Norte FMR, Brgy. Isian Norte, Leon, Iloilo', 'Brgy. Isian Norte, Leon, Iloilo', 'Leon', 'Proposed', 0),
('Opening/Construction of Sitio Hacienda, Brgy. Sto. Nino FMR, Brgy. Sto. Nino, San Miguel, Iloilo', 'Brgy. Sto. Nino, San Miguel, Iloilo', 'San Miguel', 'Proposed', 0),
('Concreting of Sitio Bacolod Sitio Agpangan, Brgy. Cabilauan FMR, Brgy. Cabilauan, New Lucena, Iloilo', 'Brgy. Cabilauan, New Lucena, Iloilo', 'New Lucena', 'Proposed', 0),
('Concreting of Sitio Uyanuyan, Brgy. Ban-ag to Brgy. Bulog FMR, Alimodian, Iloilo', 'Brgy. Ban-ag to Brgy. Bulog, Alimodian, Iloilo', 'Alimodian', 'Proposed', 0),
('Concreting of Brgy. Guihaman FMR, Brgy. Guihaman, Leganes, Iloilo', 'Brgy. Guihaman, Leganes, Iloilo', 'Leganes', 'Proposed', 0),
('Concreting of Brgy. Sto. Nino to Brgy. Sta. Teresa FMR, San Miguel, Iloilo', 'Brgy. Sto. Nino and Brgy. Sta. Teresa, San Miguel, Iloilo', 'San Miguel', 'Proposed', 0),
('Concreting of Brgy. Inagdangan Centro to Brgy. Dawis Sur FMR, Zarraga, Iloilo', 'Brgy. Inagdangan and Brgy. Dawis Sur, Zarraga, Iloilo', 'Zarraga', 'Proposed', 0),
('Concreting of Sitio Ubos to Lapayon Proper, Brgy. Lapayon FMR, Leganes, Iloilo', 'Brgy. Lapayon, Leganes, Iloilo', 'Leganes', 'Proposed', 0),
('Concreting of Brgy. Badiang to Brgy. Dawis FMR, New Lucena, Iloilo', 'Brgy. Badiang and Brgy. Dawis, New Lucena, Iloilo', 'New Lucena', 'Proposed', 0),
('Concreting of Brgy. Batuan to Brgy. Zarrague FMR, Pototan, Iloilo', 'Brgy. Batuan and Brgy. Zarrague, Pototan, Iloilo', 'Pototan', 'Proposed', 0),
('Concreting of Brgy. Talibong Grande FMR, Brgy. Talibong Grande, Mina, Iloilo', 'Brgy. Talibong Grande, Mina, Iloilo', 'Mina', 'Proposed', 0),
('Concreting of Brgy. Magsaysay to Brgy. Pianda-an East FMR, Maasin, Iloilo', 'Brgy. Magsaysay and Brgy. Pianda-an East, Maasin, Iloilo', 'Maasin', 'Proposed', 0),
('Concreting of Brgy. Dabong to Brgy. Pangilihan FMR, Janiuay, Iloilo', 'Brgy. Dabong and Brgy. Pangilihan, Janiuay, Iloilo', 'Janiuay', 'Proposed', 0),
('Concreting of Brgy. Calansanan FMR, Brgy. Calansanan, Badiangan, Iloilo', 'Brgy. Calansanan, Badiangan, Iloilo', 'Badiangan', 'Proposed', 0),
('Concreting of Brgy. Danao to Brgy. Ubang FMR, Pototan, Iloilo', 'Brgy. Danao and Brgy. Ubang, Pototan, Iloilo', 'Pototan', 'Proposed', 0),
('Concreting of Brgy. Toyungan FMR, Brgy. Toyungan, Calinog, Iloilo', 'Brgy. Toyungan, Calinog, Iloilo', 'Calinog', 'Proposed', 0),
('Concreting of Brgy. Capul-an to Brgy. Talibong Pequeno FMR, Mina, Iloilo', 'Brgy. Capul-an and Brgy. Talibong Pequeno, Mina, Iloilo', 'Mina', 'Proposed', 0),
('Concreting of Brgy. Tigbauan Road to Brgy. Tuy-an FMR, Cabatuan, Iloilo', 'Brgy. Tigbauan Road and Brgy. Tuy-an, Cabatuan, Iloilo', 'Cabatuan', 'Proposed', 0),
('Concreting of Brgy. Calansanan FMR, Brgy. Calansanan, Badiangan, Iloilo', 'Brgy. Calansanan, Badiangan, Iloilo', 'Badiangan', 'Proposed', 0),
('Concreting of Brgy. Mangil to Brgy. Manacabac FMR, Janiuay, Iloilo', 'Brgy. Manacabac, Janiuay, Iloilo', 'Janiuay', 'Proposed', 0),
('Concreting of Brgy. Badiang FMR, Brgy. Badiang, Anilao, Iloilo', 'Brgy. Badiang, Anilao, Iloilo', 'Anilao', 'Proposed', 0),
('Concreting of Brgy. Tamocol to Brgy. Agusipan FMR, Badiangan, Iloilo', 'Brgy. Tamocol and Brgy. Agusipan, Badiangan, Iloilo', 'Badiangan', 'Proposed', 0),
('Concreting of Brgy. De Lapaz FMR, Brgy. De Lapaz, Banate, Iloilo', 'Brgy. De Lapaz, Banate, Iloilo', 'Banate', 'Proposed', 0),
('Concreting of Brgy. Cabilauan FMR, Brgy. Cabilauan, Barotac Nuevo, Iloilo', 'Brgy. Cabilauan, Barotac Nuevo, Iloilo', 'Barotac Nuevo', 'Proposed', 0),
('Concreting of Brgy. Lincud FMR, Brgy. Lincud, Dingle, Iloilo', 'Brgy. Lincud, Dingle, Iloilo', 'Dingle', 'Proposed', 0),
('Concreting of Brgy. Fundacion FMR, Brgy. Fundacion, Duenas, Iloilo', 'Brgy. Fundacion, Duenas, Iloilo', 'Duenas', 'Proposed', 0),
('Concreting of Sitio Tac-on to Sitio Batuyanan, Brgy. Gemomua-Agahon FMR, Passi City, Iloilo', 'Brgy. Gemomua-Agahon, Passi City, Iloilo', 'Passi City', 'Proposed', 0),
('Concreting of Brgy. Cabugao Viejo to Brgy. Paga FMR, San Enrique, Iloilo', 'Brgy. Cabugao Viejo and Brgy. Paga, San Enrique, Iloilo', 'San Enrique', 'Proposed', 0),
('Concreting of Brgy. Dacutan FMR, Brgy. Dacutan, Dumangas, Iloilo', 'Brgy. Dacutan, Dumangas, Iloilo', 'Dumangas', 'Proposed', 0),
('Concreting of Brgy. Sto. Rosario to Brgy. Medina FMR, Anilao, Iloilo', 'Brgy. Sto. Rosario and Brgy. Medina, Anilao, Iloilo', 'Anilao', 'Proposed', 0),
('Concreting of Brgy. Cabilao Pequeno to Brgy. Cabilao Grande FMR, Carles, Iloilo', 'Brgy. Cabilao Pequeno and Brgy. Cabilao Grande, Carles, Iloilo', 'Carles', 'Proposed', 0),
('Concreting of Brgy. Lonoy FMR, Brgy. Lonoy, Estancia, Iloilo', 'Brgy. Lonoy, Estancia, Iloilo', 'Estancia', 'Proposed', 0),
('Concreting of Brgy. Tigui-an FMR, Brgy. Tingui-an, Balasan, Iloilo', 'Brgy. Tingui-an, Balasan, Iloilo', 'Balasan', 'Proposed', 0),
('Concreting of Brgy. Zerrudo FMR, Brgy. Zerrudo, Sara, Iloilo', 'Brgy. Zerrudo, Sara, Iloilo', 'Sara', 'Proposed', 0),
('Concreting of Brgy. Pangi FMR, Brgy. Pangi, San Dionisio, Iloilo', 'Brgy. Pangi, San Dionisio, Iloilo', 'San Dionisio', 'Proposed', 0),
('Concreting of Brgy. Progreso FMR, Brgy. Progreso, Ajuy, Iloilo', 'Brgy. Progreso, Ajuy, Iloilo', 'Ajuy', 'Proposed', 0),
('Concreting of Brgy. Bulak Sur FMR, Brgy. Bulak Sur, Batad, Iloilo', 'Brgy. Bulak Sur, Batad, Iloilo', 'Batad', 'Proposed', 0),
('Rehabilitation of Purok Magsaysay, Brgy. Batiti FMR, Brgy. Batiti, Concepcion, Iloilo', 'Brgy. Batiti, Concepcion, Iloilo', 'Concepcion', 'Proposed', 0),
('Concreting of Sitio Quijano, Brgy. Pontoc FMR, Brgy. Pontoc, Lemery, Iloilo', 'Brgy. Pontoc, Lemery, Iloilo', 'Lemery', 'Proposed', 0);

-- ============================================================
-- Done! Total: 100 FMR projects inserted
-- (10 On-Going + 40 Completed + 50 Proposed)
-- ============================================================
