-- ============================================================
-- KalsaTrack - LGU Leon Barangay Roads Inventory (136 roads)
-- Generated from Leon_barangay_roads.csv with barangay mapping
-- Run this in Supabase SQL Editor
-- ============================================================

CREATE TABLE IF NOT EXISTS public.lgu_road_inventory (
  id                    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  road_name             TEXT NOT NULL,
  barangay              TEXT DEFAULT '',
  municipality          TEXT DEFAULT 'Leon',
  province              TEXT DEFAULT 'Iloilo',
  classification        TEXT DEFAULT '',
  length_km             DOUBLE PRECISION DEFAULT 0,
  right_of_way_m        DOUBLE PRECISION DEFAULT 0,
  year_constructed      INTEGER,
  concrete_km           DOUBLE PRECISION,
  concrete_pct          DOUBLE PRECISION,
  concrete_condition    TEXT,
  asphalt_km            DOUBLE PRECISION,
  asphalt_pct           DOUBLE PRECISION,
  asphalt_condition     TEXT,
  gravel_km             DOUBLE PRECISION,
  gravel_pct            DOUBLE PRECISION,
  gravel_condition      TEXT,
  earth_km              DOUBLE PRECISION,
  earth_pct             DOUBLE PRECISION,
  earth_condition       TEXT,
  source                TEXT DEFAULT 'LGU Leon Barangay Roads CSV',
  created_at            TIMESTAMPTZ DEFAULT now(),
  updated_at            TIMESTAMPTZ DEFAULT now()
);

ALTER TABLE public.lgu_road_inventory ENABLE ROW LEVEL SECURITY;

CREATE POLICY IF NOT EXISTS "auth_sel_lgu_road_inventory"
  ON public.lgu_road_inventory FOR SELECT TO authenticated USING (true);
CREATE POLICY IF NOT EXISTS "anon_sel_lgu_road_inventory"
  ON public.lgu_road_inventory FOR SELECT TO anon USING (true);
CREATE POLICY IF NOT EXISTS "auth_ins_lgu_road_inventory"
  ON public.lgu_road_inventory FOR INSERT TO authenticated WITH CHECK (true);
CREATE POLICY IF NOT EXISTS "auth_upd_lgu_road_inventory"
  ON public.lgu_road_inventory FOR UPDATE TO authenticated USING (true);
CREATE POLICY IF NOT EXISTS "auth_del_lgu_road_inventory"
  ON public.lgu_road_inventory FOR DELETE TO authenticated USING (true);

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_publication_tables
    WHERE pubname = 'supabase_realtime' AND tablename = 'lgu_road_inventory'
  ) THEN
    ALTER PUBLICATION supabase_realtime ADD TABLE public.lgu_road_inventory;
  END IF;
END $$;

INSERT INTO public.lgu_road_inventory (
  road_name, barangay, municipality, classification, length_km,
  right_of_way_m, year_constructed,
  concrete_km, concrete_pct, concrete_condition,
  asphalt_km, asphalt_pct, asphalt_condition,
  gravel_km, gravel_pct, gravel_condition,
  earth_km, earth_pct, earth_condition
) VALUES
  ('Agboy Norte-Siol Norte Rd', 'Agboy Norte', 'Leon', 'Iloilo', 'Barangay Rd', 1.47, 6, 2013, 0.03, 2, 'Fair', NULL, NULL, NULL, NULL, NULL, NULL, 1.44, 98, 'Poor'),
  ('Agta Road', 'Agta', 'Leon', 'Iloilo', 'Barangay Rd', 0.85, 6, 1983, 0.41, 48, 'Fair', NULL, NULL, NULL, 0.45, 52, 'Fair', NULL, NULL, NULL),
  ('Anonang-Sitio Bangalad', 'Anonang', 'Leon', 'Iloilo', 'Barangay Rd', 0.62, 6, 2013, 0.05, 8, 'Fair', NULL, NULL, NULL, 0.41, 66, 'Fair', 0.16, 26, 'Poor'),
  ('Apian Road', 'Apian', 'Leon', 'Iloilo', 'Barangay Rd', 0.96, 6, 1984, 0.77, 80, 'Fair', NULL, NULL, NULL, 0.19, 20, 'Fair', NULL, NULL, NULL),
  ('Apian-Coyugan Norte Rd', 'Apian', 'Leon', 'Iloilo', 'Barangay Rd', 0.78, 6, 1998, 0.08, 10, 'Fair', NULL, NULL, NULL, 0.7, 90, 'Fair', NULL, NULL, NULL),
  ('Avanzada-Baje Road', 'Avanzada', 'Leon', 'Iloilo', 'Barangay Rd', 9.36, 6, 1983, 6.76, 72, 'Fair', NULL, NULL, NULL, 2.6, 28, 'Poor', NULL, NULL, NULL),
  ('Awis Road', 'Awis', 'Leon', 'Iloilo', 'Barangay Rd', 0.18, 6, 1997, 0.01, 8, 'Fair', NULL, NULL, NULL, 0.17, 92, 'Fair', NULL, NULL, NULL),
  ('Ayabang Road', 'Ayabang', 'Leon', 'Iloilo', 'Barangay Rd', 0.74, 6, 2000, NULL, NULL, NULL, NULL, NULL, NULL, 0.74, 100, 'Poor', NULL, NULL, NULL),
  ('Ayubo Road', 'Ayubo', 'Leon', 'Iloilo', 'Barangay Rd', 0.13, 6, 2022, 0.13, 100, 'Fair', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
  ('Bacolod Road', 'Bacolod', 'Leon', 'Iloilo', 'Barangay Rd', 1.05, 6, 1999, 1.05, 100, 'Fair', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
  ('Bacolod-Cabunga-an Rd.', 'Bacolod', 'Leon', 'Iloilo', 'Barangay Rd', 1.26, 6, 2022, 1.26, 100, 'Fair', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
  ('Banagan Road', 'Banagan', 'Leon', 'Iloilo', 'Barangay Rd', 1.27, 6, 1999, 0.98, 78, 'Fair', NULL, NULL, NULL, 0.28, 22, 'Poor', NULL, NULL, NULL),
  ('Barangbang Road', 'Barangbang', 'Leon', 'Iloilo', 'Barangay Rd', 1.55, 6, 1983, 0.88, 57, 'Fair', NULL, NULL, NULL, NULL, NULL, NULL, 0.66, 43, 'Poor'),
  ('Barasan Road', 'Barasan', 'Leon', 'Iloilo', 'Barangay Rd', 0.55, 6, 1983, 0.55, 100, 'Fair', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
  ('Bayag Norte-Sitio Danao Rd', 'Bayag Norte', 'Leon', 'Iloilo', 'Barangay Rd', 0.36, 6, 2015, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0.36, 100, 'Poor'),
  ('Bayag Norte-Sitio Raug Rd', 'Bayag Norte', 'Leon', 'Iloilo', 'Barangay Rd', 0.53, 6, 2015, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0.53, 100, 'Poor'),
  ('Binolbog Road', 'Binolbog', 'Leon', 'Iloilo', 'Barangay Rd', 0.69, 6, 2000, 0.21, 31, 'Poor', NULL, NULL, NULL, 0.48, 69, 'Poor', NULL, NULL, NULL),
  ('Binolbog Road (new)', 'Binolbog Road (new)', 'Leon', 'Iloilo', 'Barangay Rd', 0.48, 6, 2020, NULL, NULL, NULL, NULL, NULL, NULL, 0.48, 100, 'Fair', NULL, NULL, NULL),
  ('Binolbog-Ambulong Road', 'Binolbog', 'Leon', 'Iloilo', 'Barangay Rd', 2.28, 6, 2015, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 2.28, 100, 'Poor'),
  ('Biri Norte-Isian Norte Road', 'Biri Norte', 'Leon', 'Iloilo', 'Barangay Rd', 2.65, 6, 2000, 0.58, 22, 'Fair', NULL, NULL, NULL, 2.07, 78, 'Poor', NULL, NULL, NULL),
  ('Biri Norte-Tina-an Sur Road', 'Biri Norte', 'Leon', 'Iloilo', 'Barangay Rd', 2.73, 6, 2000, NULL, NULL, NULL, NULL, NULL, NULL, 2.73, 100, 'Poor', NULL, NULL, NULL),
  ('Biri Sur Road', 'Biri Sur', 'Leon', 'Iloilo', 'Barangay Rd', 0.78, 6, 2010, 0.45, 58, 'Fair', NULL, NULL, NULL, NULL, NULL, NULL, 0.33, 42, 'Poor'),
  ('Biri Sur-Sitio Dulaca Road', 'Biri Sur', 'Leon', 'Iloilo', 'Barangay Rd', 1.21, 6, 2019, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 1.21, 100, 'Poor'),
  ('Bucari Road', 'Bucari', 'Leon', 'Iloilo', 'Barangay Rd', 0.99, 6, 1983, 0.99, 100, 'Fair', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
  ('Bucari Road', 'Bucari', 'Leon', 'Iloilo', 'Barangay Rd', 0.09, 6, 1983, 0.09, 100, 'Poor', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
  ('Bucari-Cagay-Ingay Road', 'Bucari', 'Leon', 'Iloilo', 'Barangay Rd', 4.54, 10, 2000, 1.1, 24, 'Poor', NULL, NULL, NULL, 1.91, 42, 'Fair', 1.53, 34, 'Poor'),
  ('Bucari-Camandag Road', 'Bucari', 'Leon', 'Iloilo', 'Barangay Rd', 3.02, 10, 1998, 3.02, 100, 'Fair', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
  ('Bucari-Cumpan-Sibucao', 'Bucari', 'Leon', 'Iloilo', 'Barangay Rd', 2.11, 6, 2000, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 2.11, 100, 'Critical'),
  ('Bucari-Tabionan Road', 'Bucari', 'Leon', 'Iloilo', 'Barangay Rd', 0.44, 6, 2000, NULL, NULL, NULL, NULL, NULL, NULL, 0.44, 100, 'Fair', NULL, NULL, NULL),
  ('Buga Road', 'Buga', 'Leon', 'Iloilo', 'Barangay Rd', 1.5, 10, 1960, 1.5, 100, 'Fair', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
  ('Buga-Sitio Dao-Baong Rd.', 'Buga', 'Leon', 'Iloilo', 'Barangay Rd', 2.46, 6, 2014, NULL, NULL, NULL, NULL, NULL, NULL, 0.39, 16, 'Fair', 2.08, 84, 'Fair'),
  ('Buga-Kananghan-Iguaras', 'Buga', 'Leon', 'Iloilo', 'Barangay Rd', 3.82, 4, 2009, 0.14, 4, 'Fair', NULL, NULL, NULL, 3.24, 85, 'Poor', 0.44, 11, 'Poor'),
  ('Buga-Jct-Kananghan Rd', 'Buga', 'Leon', 'Iloilo', 'Barangay Road', 0.29, 4, 2009, NULL, NULL, NULL, NULL, NULL, NULL, 0.29, 100, 'Poor', NULL, NULL, NULL),
  ('Buga-Jct-Lampigaw-Pinon-an Road', 'Buga', 'Leon', 'Iloilo', 'Barangay Road', 2.97, 4, 2010, NULL, NULL, NULL, NULL, NULL, NULL, 0.91, 31, 'Poor', 2.06, 69, 'Poor'),
  ('Buga-Sitio Bugtong Road', 'Buga', 'Leon', 'Iloilo', 'Barangay Road', 0.13, 4, 2005, 0.13, 100, 'Fair', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
  ('Buga-Sitio Tibod-Lanag Rd', 'Buga', 'Leon', 'Iloilo', 'Barangay Road', 1.9, 6, 2009, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 1.9, 100, 'Poor'),
  ('Bulad Road', 'Bulad', 'Leon', 'Iloilo', 'Barangay Road', 0.87, 6, 1997, 0.8, 92, 'Fair', NULL, NULL, NULL, 0.07, 8, 'Fair', NULL, NULL, NULL),
  ('Cabunga-an-Caboloan Rd', 'Cabunga', 'Leon', 'Iloilo', 'Barangay Road', 1.87, 10, 2001, 1.87, 100, 'Fair', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
  ('Cabutongan Road', 'Cabutongan', 'Leon', 'Iloilo', 'Barangay Road', 0.71, 6, 1984, 0.71, 100, 'Fair', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
  ('Cagay Road', 'Cagay', 'Leon', 'Iloilo', 'Barangay Road', 0.3, 6, 2000, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0.3, 100, 'Poor'),
  ('Camandag-Bobon Road', 'Camandag', 'Leon', 'Iloilo', 'Barangay Road', 1.75, 10, 1999, 1.75, 100, 'Fair', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
  ('Camandag-Bulwang Rd', 'Camandag', 'Leon', 'Iloilo', 'Barangay Road', 0.8, 6, 1998, 0.8, 100, 'Fair', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
  ('Cananaman Road', 'Cananaman', 'Leon', 'Iloilo', 'Barangay Road', 2.05, 6, 1984, 2.05, 100, 'Fair', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
  ('Capt. Fernando-Paoy Rd', 'Capt. Fernando', 'Leon', 'Iloilo', 'Barangay Road', 0.75, 6, 1997, NULL, NULL, NULL, NULL, NULL, NULL, 0.75, 100, 'Fair', NULL, NULL, NULL),
  ('Capt. Fernando-Sitio Limotan Road', 'Capt. Fernando', 'Leon', 'Iloilo', 'Barangay Road', 0.68, 6, 2022, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0.68, 100, 'Poor'),
  ('Capt. Fernando-Lang-og Rd.', 'Capt. Fernando', 'Leon', 'Iloilo', 'Barangay Road', 0.51, 6, 2022, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0.51, 100, 'Poor'),
  ('Carara-an-Sitio Talibong Rd', 'Carara', 'Leon', 'Iloilo', 'Barangay Road', 1.94, 6, 2022, 1.94, 100, 'Fair', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
  ('Carolina Road', 'Carolina', 'Leon', 'Iloilo', 'Barangay Road', 0.8, 6, 1998, 0.8, 100, 'Fair', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
  ('Carolina Rd. Jct Langog Rd', 'Carolina Rd. Jct Langog', 'Leon', 'Iloilo', 'Barangay Road', 0.83, 6, 1992, 0.43, 51, 'Fair', NULL, NULL, NULL, NULL, NULL, NULL, 0.4, 49, 'Poor'),
  ('Coyugan Norte Road', 'Coyugan Norte', 'Leon', 'Iloilo', 'Barangay Road', 0.53, 6, 1998, 0.23, 43, 'Fair', NULL, NULL, NULL, 0.3, 57, 'Poor', NULL, NULL, NULL),
  ('Coyugan Sur Road', 'Coyugan Sur', 'Leon', 'Iloilo', 'Barangay Road', 0.76, 6, 1983, 0.76, 100, 'Fair', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
  ('Coyugan Sur Road New', 'Coyugan Sur Road New', 'Leon', 'Iloilo', 'Barangay Road', 0.39, 6, 2022, 0.39, 100, 'Fair', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
  ('Danao Road', 'Danao', 'Leon', 'Iloilo', 'Barangay Road', 1.5, 6, 2022, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 1.5, 100, 'Poor'),
  ('Dorog Road', 'Dorog', 'Leon', 'Iloilo', 'Barangay Road', 0.63, 6, 1983, 0.63, 100, 'Fair', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
  ('Dorog-Marirong Road', 'Dorog', 'Leon', 'Iloilo', 'Barangay Road', 3.02, 6, 2017, 2.94, 97, 'Fair', NULL, NULL, NULL, NULL, NULL, NULL, 0.08, 3, 'Poor'),
  ('Dorog-Carara-an Road', 'Dorog', 'Leon', 'Iloilo', 'Barangay Road', 1.92, 6, 1998, 1.22, 64, 'Fair', NULL, NULL, NULL, 0.7, 36, 'Fair', NULL, NULL, NULL),
  ('Dorog-Cawilihan Road', 'Dorog', 'Leon', 'Iloilo', 'Barangay Road', 2.62, 6, 2009, 0.13, 5, 'Fair', NULL, NULL, NULL, 2.49, 95, 'Fair', NULL, NULL, NULL),
  ('Dusacan Road (new)', 'Dusacan Road (new)', 'Leon', 'Iloilo', 'Barangay Road', 0.27, 6, 2022, NULL, NULL, NULL, NULL, NULL, NULL, 0.27, 100, 'Poor', NULL, NULL, NULL),
  ('Gines Brgy. Proper New Rd', 'Gines Brgy. Proper New', 'Leon', 'Iloilo', 'Barangay Road', 0.39, 6, 2021, 0.39, 100, 'Fair', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
  ('Gines-Ayabang Road', 'Gines', 'Leon', 'Iloilo', 'Barangay Road', 0.75, 6, 2001, 0.64, 84, 'Fair', NULL, NULL, NULL, NULL, NULL, NULL, 0.12, 16, 'Poor'),
  ('Gines-Ticuan Road', 'Gines', 'Leon', 'Iloilo', 'Barangay Road', 0.91, 6, 2001, 0.91, 100, 'Fair', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
  ('Gines-Tunguan Road', 'Gines', 'Leon', 'Iloilo', 'Barangay Road', 2.1, 6, 2001, 1.34, 64, 'Fair', NULL, NULL, NULL, 0.76, 36, 'Fair', NULL, NULL, NULL),
  ('Gines-Sitio Mayang', 'Gines', 'Leon', 'Iloilo', 'Barangay Road', 0.49, 10, 2022, 0.49, 100, 'Fair', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
  ('Gumboc-Awis-Paoy-Camando Road', 'Gumboc', 'Leon', 'Iloilo', 'Barangay Road', 5.11, 6, 1984, 1.1, 22, 'Fair', NULL, NULL, NULL, 4.01, 78, 'Fair', NULL, NULL, NULL),
  ('Gumboc-Jct Capt. Fernando Road', 'Gumboc', 'Leon', 'Iloilo', 'Barangay Road', 0.99, 6, 1984, 0.54, 54, 'Fair', NULL, NULL, NULL, 0.45, 46, 'Fair', NULL, NULL, NULL),
  ('Gumboc-Sitio Biasong', 'Gumboc', 'Leon', 'Iloilo', 'Barangay Road', 0.57, 6, 2022, NULL, NULL, NULL, NULL, NULL, NULL, 0.57, 100, 'Fair', NULL, NULL, NULL),
  ('Gumboc-Sitio Taal', 'Gumboc', 'Leon', 'Iloilo', 'Barangay Road', 0.43, 6, 2022, NULL, NULL, NULL, NULL, NULL, NULL, 0.43, 100, 'Fair', NULL, NULL, NULL),
  ('Igcadios Road', 'Igcadios', 'Leon', 'Iloilo', 'Barangay Road', 0.85, 6, 1983, 0.33, 39, 'Fair', NULL, NULL, NULL, 0.52, 61, 'Fair', NULL, NULL, NULL),
  ('Igcadios-Ayabang Road', 'Igcadios', 'Leon', 'Iloilo', 'Barangay Road', 1.18, 6, 2009, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 1.18, 100, 'Poor'),
  ('Igcadios-Carara-an Road', 'Igcadios', 'Leon', 'Iloilo', 'Barangay Road', 0.96, 6, 2022, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0.96, 100, 'Poor'),
  ('Isian Norte-Casling Road', 'Isian Norte', 'Leon', 'Iloilo', 'Barangay Road', 1.67, 6, 1999, 0.81, 48, 'Fair', NULL, NULL, NULL, 0.86, 52, 'Fair', NULL, NULL, NULL),
  ('Isian Norte-Sitio Gaspangan', 'Isian Norte', 'Leon', 'Iloilo', 'Barangay Road', 0.27, 6, 2019, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0.27, 100, 'Fair'),
  ('Isian Norte-Sitio Lanag', 'Isian Norte', 'Leon', 'Iloilo', 'Barangay Road', 0.58, 6, 1999, 0.58, 100, 'Fair', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
  ('Isian Norte-Sitio Lanag-Isian Victoria Road', 'Isian Norte', 'Leon', 'Iloilo', 'Barangay Road', 0.77, 6, 2022, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0.77, 100, 'Poor'),
  ('Isian Victoria Road', 'Isian Victoria', 'Leon', 'Iloilo', 'Barangay Road', 2.89, 6, 2002, 0.49, 17, 'Fair', NULL, NULL, NULL, NULL, NULL, NULL, 2.39, 83, 'Poor'),
  ('Jamog Gines Road', 'Jamog Gines', 'Leon', 'Iloilo', 'Barangay Road', 0.14, 6, 2005, 0.14, 100, 'Fair', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
  ('Jamog Gines Road', 'Jamog Gines', 'Leon', 'Iloilo', 'Barangay Road', 0.3, 6, 2017, 0.15, 50, 'Fair', NULL, NULL, NULL, 0.15, 50, 'Good', NULL, NULL, NULL),
  ('Lanag-ISAT U Demo Farm Rd', 'Lanag', 'Leon', 'Iloilo', 'Barangay Road', 1.19, 6, 2021, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 1.19, 100, 'Poor'),
  ('Lang-og Road', 'Lang', 'Leon', 'Iloilo', 'Barangay Road', 0.98, 6, 1982, 0.98, 100, 'Fair', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
  ('Lanag Road', 'Lanag', 'Leon', 'Iloilo', 'Barangay Road', 1.18, 6, 1982, 0.97, 82, 'Fair', NULL, NULL, NULL, 0.21, 18, 'Poor', NULL, NULL, NULL),
  ('Lanag-Nagbangi-Tuog', 'Lanag', 'Leon', 'Iloilo', 'Barangay Road', 3.56, 6, 1999, 1.5, 42, 'Fair', NULL, NULL, NULL, 2.06, 58, 'Fair', NULL, NULL, NULL),
  ('Lanag (going to Don Felimon Inland Resort', 'Lanag (going to Don Felimon Inland Resort', 'Leon', 'Iloilo', 'Barangay Road', 1.25, 6, 2021, NULL, NULL, NULL, NULL, NULL, NULL, 1.25, 100, 'Poor', NULL, NULL, NULL),
  ('Lanag-Sitio Puro Gamay', 'Lanag', 'Leon', 'Iloilo', 'Barangay Road', 0.51, 6, 2001, NULL, NULL, NULL, NULL, NULL, NULL, 0.51, 100, 'Fair', NULL, NULL, NULL),
  ('Lanag-Tu-og Road', 'Lanag', 'Leon', 'Iloilo', 'Barangay Road', 0.93, 6, 2022, NULL, NULL, NULL, NULL, NULL, NULL, 0.18, 19, 'Fair', 0.75, 81, 'Poor'),
  ('Ligtos Road', 'Ligtos', 'Leon', 'Iloilo', 'Barangay Road', 0.47, 6, 1984, 0.43, 91, 'Fair', NULL, NULL, NULL, 0.04, 9, 'Fair', NULL, NULL, NULL),
  ('Ligtos-Gines Road', 'Ligtos', 'Leon', 'Iloilo', 'Barangay Road', 5.49, 10, 1984, 2.35, 43, 'Fair', NULL, NULL, NULL, 3.14, 57, 'Fair', NULL, NULL, NULL),
  ('Magcapay-Sitio Kalapadan Road', 'Magcapay', 'Leon', 'Iloilo', 'Barangay Road', 0.55, 6, 2018, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0.55, 100, 'Poor'),
  ('Magcapay-Sitio Bungad Rd', 'Magcapay', 'Leon', 'Iloilo', 'Barangay Road', 0.48, 6, 2022, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0.48, 100, 'Poor'),
  ('Magcapay Road', 'Magcapay', 'Leon', 'Iloilo', 'Barangay Road', 1.75, 6, 2009, 1.09, 63, 'Fair', NULL, NULL, NULL, 0.65, 37, 'Poor', NULL, NULL, NULL),
  ('Maliao Road', 'Maliao', 'Leon', 'Iloilo', 'Barangay Road', 0.28, 6, 1999, NULL, NULL, NULL, NULL, NULL, NULL, 0.28, 100, 'Fair', NULL, NULL, NULL),
  ('Maliao-Cabunga-an Rd', 'Maliao', 'Leon', 'Iloilo', 'Barangay Road', 2.65, 6, 1997, 0.56, 21, 'Fair', NULL, NULL, NULL, 2.09, 79, 'Poor', NULL, NULL, NULL),
  ('Maliao-Lampaya Road', 'Maliao', 'Leon', 'Iloilo', 'Barangay Road', 1.76, 6, 2001, 0.39, 22, 'Fair', NULL, NULL, NULL, 1.37, 78, 'Poor', NULL, NULL, NULL),
  ('Malublub Road', 'Malublub', 'Leon', 'Iloilo', 'Barangay Road', 1.87, 6, 1998, 1.29, 69, 'Fair', NULL, NULL, NULL, 0.59, 31, 'Fair', NULL, NULL, NULL),
  ('Malublub-Abang-Abang Rd', 'Malublub', 'Leon', 'Iloilo', 'Barangay Road', 2.24, 6, 2009, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 2.24, 100, 'Poor'),
  ('Malublub-Sitio Lintian Rd', 'Malublub', 'Leon', 'Iloilo', 'Barangay Road', 2, 6, 2017, NULL, NULL, NULL, NULL, NULL, NULL, 2, 100, 'Fair', NULL, NULL, NULL),
  ('Malublub-Sitio Buyo', 'Malublub', 'Leon', 'Iloilo', 'Barangay Road', 0.89, 6, 2018, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0.89, 100, 'Poor'),
  ('Malublub-Sitio Tumotob', 'Malublub', 'Leon', 'Iloilo', 'Barangay Road', 1.82, 6, 2018, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 1.82, 100, 'Poor'),
  ('Manampunay-Tac. Norte Rd', 'Manampunay', 'Leon', 'Iloilo', 'Barangay Road', 2.1, 10, 1999, 1.23, 58, 'Fair', NULL, NULL, NULL, 0.87, 42, 'Fair', NULL, NULL, NULL),
  ('Marirong Road', 'Marirong', 'Leon', 'Iloilo', 'Barangay Road', 0.29, 6, 2018, 0.29, 100, 'Fair', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
  ('Mina Road', 'Mina', 'Leon', 'Iloilo', 'Barangay Road', 0.84, 6, 2005, 0.29, 35, 'Fair', NULL, NULL, NULL, 0.55, 65, 'Fair', NULL, NULL, NULL),
  ('Mocol Road', 'Mocol', 'Leon', 'Iloilo', 'Barangay Road', 0.45, 6, 1983, 0.45, 100, 'Fair', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
  ('Nagbangi Road', 'Nagbangi', 'Leon', 'Iloilo', 'Barangay Road', 0.32, 6, 1983, NULL, NULL, NULL, NULL, NULL, NULL, 0.32, 100, 'Fair', NULL, NULL, NULL),
  ('Nagbangi-Siol Norte-Agboy Sur Road', 'Nagbangi', 'Leon', 'Iloilo', 'Barangay Road', 3.8, 6, 1999, 1.36, 36, 'Fair', NULL, NULL, NULL, 2.45, 64, 'Fair', NULL, NULL, NULL),
  ('Nalbang Road', 'Nalbang', 'Leon', 'Iloilo', 'Barangay Road', 0.43, 6, 1983, 0.43, 100, 'Fair', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
  ('Odong-Odong Road', 'Odong', 'Leon', 'Iloilo', 'Barangay Road', 1.01, 6, 1983, 0.52, 51, 'Fair', NULL, NULL, NULL, 0.5, 49, 'Fair', NULL, NULL, NULL),
  ('Oluangan Road', 'Oluangan', 'Leon', 'Iloilo', 'Barangay Road', 2.11, 6, 1983, 0.92, 44, 'Fair', NULL, NULL, NULL, 1.19, 56, 'Fair', NULL, NULL, NULL),
  ('Paga Road', 'Paga', 'Leon', 'Iloilo', 'Barangay Road', 1.51, 6, 2022, 1.51, 100, 'Fair', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
  ('Pandan-Buenavista Rd.', 'Pandan', 'Leon', 'Iloilo', 'Barangay Road', 1.57, 6, 1983, 1.57, 100, 'Fair', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
  ('Pandan-Barawbaraw Rd', 'Pandan', 'Leon', 'Iloilo', 'Barangay Road', 0.87, 6, 2022, NULL, NULL, NULL, NULL, NULL, NULL, 0.87, 100, 'Fair', NULL, NULL, NULL),
  ('Pandan-Composting Center Road', 'Pandan', 'Leon', 'Iloilo', 'Barangay Road', 0.45, 6, 1994, NULL, NULL, NULL, NULL, NULL, NULL, 0.45, 100, 'Fair', NULL, NULL, NULL),
  ('Paoy Road', 'Paoy', 'Leon', 'Iloilo', 'Barangay Road', 0.6, 6, 1997, 0.11, 18, 'Fair', NULL, NULL, NULL, NULL, NULL, NULL, 0.49, 82, 'Poor'),
  ('Pepe-Binolbog Road', 'Pepe', 'Leon', 'Iloilo', 'Barangay Road', 1.16, 6, 1983, 0.04, 3, 'Poor', NULL, NULL, NULL, 0.04, 3, 'Poor', 1.09, 93, 'Poor'),
  ('Poblacion-Sitio Buntalan Sitio Dugo Road', 'Poblacion', 'Leon', 'Iloilo', 'Barangay Road', 0.44, 10, 2018, 0.44, 100, 'Fair', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
  ('Poblacion-Sitio Dugo Rd', 'Poblacion', 'Leon', 'Iloilo', 'Barangay Road', 1.03, 10, 2005, 0.4, 38, 'Fair', NULL, NULL, NULL, 0.64, 62, 'Fair', NULL, NULL, NULL),
  ('Poblacion-Sitio Miac-ac', 'Poblacion', 'Leon', 'Iloilo', 'Barangay Road', 1.77, 6, 2005, 1.08, 61, 'Fair', NULL, NULL, NULL, 0.7, 39, 'Fair', NULL, NULL, NULL),
  ('Salngan Road', 'Salngan', 'Leon', 'Iloilo', 'Barangay Road', 1.12, 6, 1986, 0.46, 41, 'Fair', NULL, NULL, NULL, 0.66, 59, 'Fair', NULL, NULL, NULL),
  ('Salngan-Isian Victoria Rd', 'Salngan', 'Leon', 'Iloilo', 'Barangay Road', 1.01, 6, 1986, 0.87, 86, 'Fair', NULL, NULL, NULL, 0.14, 14, 'Fair', NULL, NULL, NULL),
  ('Samlague Road', 'Samlague', 'Leon', 'Iloilo', 'Barangay Road', 1, 6, 2010, 0.86, 86, 'Fair', NULL, NULL, NULL, 0.14, 14, 'Fair', NULL, NULL, NULL),
  ('Siol Sur Road', 'Siol Sur', 'Leon', 'Iloilo', 'Barangay Road', 0.36, 6, 2005, 0.36, 100, 'Fair', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
  ('Siol Sur-Anonang Road', 'Siol Sur', 'Leon', 'Iloilo', 'Barangay Road', 1.24, 6, 2016, NULL, NULL, NULL, NULL, NULL, NULL, 1.24, 100, 'Fair', NULL, NULL, NULL),
  ('Tacuyong Norte Road', 'Tacuyong Norte', 'Leon', 'Iloilo', 'Barangay Road', 0.57, 6, 1999, 0.57, 100, 'Fair', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
  ('Tac. Norte-Marirong Rd.', 'Tac. Norte', 'Leon', 'Iloilo', 'Barangay Road', 0.82, 6, 1986, 0.82, 100, 'Fair', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
  ('Tacuyong Sur Road', 'Tacuyong Sur', 'Leon', 'Iloilo', 'Barangay Road', 0.59, 6, 1982, 0.59, 100, 'Fair', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
  ('Tac. Sur-Baje Road', 'Tac. Sur', 'Leon', 'Iloilo', 'Barangay Road', 2.24, 6, 2003, 1.92, 86, 'Fair', NULL, NULL, NULL, 0.32, 14, 'Fair', NULL, NULL, NULL),
  ('Tagsing Road', 'Tagsing', 'Leon', 'Iloilo', 'Barangay Road', 1.76, 6, 1983, 0.6, 34, 'Fair', NULL, NULL, NULL, 1.16, 66, 'Fair', NULL, NULL, NULL),
  ('Talacu-an-Takasi-Panginman Road', 'Talacu', 'Leon', 'Iloilo', 'Barangay Road', 0.81, 6, 2009, 0.51, 63, 'Fair', NULL, NULL, NULL, 0.3, 37, 'Poor', NULL, NULL, NULL),
  ('Takasi-Bunga Road', 'Takasi', 'Leon', 'Iloilo', 'Barangay Road', 0.39, 6, 2021, NULL, NULL, NULL, NULL, NULL, NULL, 0.39, 100, 'Fair', NULL, NULL, NULL),
  ('Tina-an Norte Road', 'Tina', 'Leon', 'Iloilo', 'Barangay Road', 0.73, 6, 1961, 0.73, 100, 'Fair', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
  ('Tina-an Norte-Sitio Bugo', 'Tina', 'Leon', 'Iloilo', 'Barangay Road', 0.47, 4, 2022, 0.14, 30, 'Fair', NULL, NULL, NULL, 0.33, 70, 'Poor', NULL, NULL, NULL),
  ('Tunguan-Lampaya Road', 'Tunguan', 'Leon', 'Iloilo', 'Barangay Road', 1.5, 6, 2017, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 1.5, 100, 'Poor'),
  ('Tunguan-Banagan Road', 'Tunguan', 'Leon', 'Iloilo', 'Barangay Road', 1.51, 6, 2005, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 1.51, 100, 'Poor'),
  ('Tu-og Road', 'Tu', 'Leon', 'Iloilo', 'Barangay Road', 0.41, 6, 2022, 0.07, 17, 'Fair', NULL, NULL, NULL, 0.34, 83, 'Fair', 0, 0, 'Poor'),
  ('Tu-og-Lanot Road', 'Tu', 'Leon', 'Iloilo', 'Barangay Road', 0.55, 6, 2000, 0.19, 35, 'Fair', NULL, NULL, NULL, 0.36, 65, 'Fair', NULL, NULL, NULL),
  ('Tu-og-Siol Norte Road', 'Tu', 'Leon', 'Iloilo', 'Barangay Road', 1.44, 6, 2022, NULL, NULL, 'Fair', NULL, NULL, NULL, NULL, NULL, NULL, 1.44, 100, 'Poor'),
  ('Dorog-Marirong-Dorog', 'Dorog', 'Leon', 'Iloilo', 'Barangay Road', 0.9, 6, 2022, 0.9, 100, 'Good', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
  ('Cemetery Road.', 'Cemetery', 'Leon', 'Iloilo', 'Barangay Road', 0.9, 6, 2022, 0.9, 100, 'Good', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);

-- ============================================================
-- Done! 136 roads, 176.51 km total
-- Barangays matched: 136/136
-- ============================================================