-- ============================================================
-- Create / Recreate the projects table + RLS policies
-- Run this SQL in your Supabase SQL Editor
-- ============================================================

-- 1. Drop the old table so we start fresh (removes old policies too)
DROP TABLE IF EXISTS public.projects CASCADE;

-- 2. Create the projects table
CREATE TABLE public.projects (
  id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "projectName"   TEXT NOT NULL DEFAULT '',
  "projectCode"   TEXT DEFAULT '',
  region          TEXT DEFAULT '',
  province        TEXT DEFAULT '',
  municipality    TEXT DEFAULT '',
  barangay        TEXT DEFAULT '',
  latitude        DOUBLE PRECISION DEFAULT 0,
  longitude       DOUBLE PRECISION DEFAULT 0,
  "roadLength"    DOUBLE PRECISION DEFAULT 0,
  "roadWidth"     DOUBLE PRECISION DEFAULT 0,
  "roadType"      TEXT DEFAULT '',
  "totalBudget"   DOUBLE PRECISION DEFAULT 0,
  "budgetSource"  TEXT DEFAULT '',
  "disbursedAmount" DOUBLE PRECISION DEFAULT 0,
  contractor      TEXT DEFAULT '',
  "startDate"     TEXT DEFAULT '',
  "expectedEndDate" TEXT DEFAULT '',
  status          TEXT NOT NULL DEFAULT 'Planning',
  progress        INTEGER DEFAULT 0,
  description     TEXT DEFAULT '',
  created_at      TIMESTAMPTZ DEFAULT now(),
  updated_at      TIMESTAMPTZ DEFAULT now()
);

-- 3. Enable Row Level Security
ALTER TABLE public.projects ENABLE ROW LEVEL SECURITY;

-- 4. RLS Policies
CREATE POLICY "Anyone authenticated can view projects"
  ON public.projects FOR SELECT TO authenticated USING (true);

CREATE POLICY "Authenticated users can insert projects"
  ON public.projects FOR INSERT TO authenticated WITH CHECK (true);

CREATE POLICY "Authenticated users can update projects"
  ON public.projects FOR UPDATE TO authenticated USING (true);

CREATE POLICY "Authenticated users can delete projects"
  ON public.projects FOR DELETE TO authenticated USING (true);

-- 5. Enable realtime for projects
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_publication_tables
    WHERE pubname = 'supabase_realtime' AND tablename = 'projects'
  ) THEN
    ALTER PUBLICATION supabase_realtime ADD TABLE public.projects;
  END IF;
END $$;
