-- ============================================================
-- Supabase Migration: project_routes table
-- Department of Agriculture - RAED Region VI
-- Stores the drawn/defined road route (start/end points + waypoints)
-- for each fmr_projects row. Run this SQL in your Supabase SQL Editor.
--
-- Root cause: the app code (Dashboard.jsx, UserMapView.jsx,
-- FarmerDashboard.jsx, PublicReportForm.jsx, etc.) has always
-- referenced a `project_routes` table, but it was never created in
-- this Supabase project. Reads silently fall back to "no route" and
-- writes (the DA Admin "Define Route" action) silently fail, which is
-- why routes never get recorded. This migration creates the table.
-- ============================================================

-- 1. Create the project_routes table
CREATE TABLE IF NOT EXISTS public.project_routes (
  id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  project_id      BIGINT NOT NULL UNIQUE REFERENCES public.fmr_projects(id) ON DELETE CASCADE,
  start_latitude  DOUBLE PRECISION,
  start_longitude DOUBLE PRECISION,
  end_latitude    DOUBLE PRECISION,
  end_longitude   DOUBLE PRECISION,
  route_points    JSONB DEFAULT '[]'::jsonb,
  created_at      TIMESTAMPTZ DEFAULT now(),
  updated_at      TIMESTAMPTZ DEFAULT now()
);

-- 2. Enable Row Level Security
ALTER TABLE public.project_routes ENABLE ROW LEVEL SECURITY;

-- 3. RLS Policies
-- Routes are read by public report forms and public-facing map views,
-- so SELECT, INSERT, UPDATE, and DELETE are open to anon + authenticated.
CREATE POLICY "Anyone can view project_routes"
  ON public.project_routes FOR SELECT TO anon, authenticated USING (true);

CREATE POLICY "Anyone can insert project_routes"
  ON public.project_routes FOR INSERT TO anon, authenticated WITH CHECK (true);

CREATE POLICY "Anyone can update project_routes"
  ON public.project_routes FOR UPDATE TO anon, authenticated USING (true);

CREATE POLICY "Anyone can delete project_routes"
  ON public.project_routes FOR DELETE TO anon, authenticated USING (true);

-- Grant privileges to anon and authenticated roles
GRANT ALL ON TABLE public.project_routes TO postgres, anon, authenticated, service_role;

-- 4. Enable Realtime
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_publication_tables
    WHERE pubname = 'supabase_realtime' AND tablename = 'project_routes'
  ) THEN
    ALTER PUBLICATION supabase_realtime ADD TABLE public.project_routes;
  END IF;
END $$;

-- ============================================================
-- Done. The DA Admin "Define Route" action upserts onto
-- project_routes(project_id) with onConflict: 'project_id', which
-- requires the UNIQUE constraint on project_id created above.
-- ============================================================
