-- ============================================================
-- KalsaTrack - Road Network Gaps (schema only)
--
-- A "road network gap" is the UNPAVED portion of a surveyed barangay road: the
-- Earth and/or Gravel sub-segments recorded in Leon_barangay_roads.csv. It is not
-- an invented quantity -- gap_km is the sum of that road's Earth + Gravel lengths
-- as surveyed by the LGU, which is why gap lengths vary naturally (0.04 to 4.01 km
-- across 104 of Leon's 143 roads).
--
-- This replaces two earlier, disconnected notions of a gap:
--   1. src/components/lgu/LguRouteMap.jsx had FOUR hardcoded demo gap segments
--      with hand-typed coordinates, all terminating at the Leon market point. The
--      code comment said "Simulated" but the UI label did not, so LGU users saw
--      them as real.
--   2. src/lib/priorityScoring.js computed a gap per project from a fallback
--      chain, unconnected to anything drawn on the map, so the two could disagree.
--
-- Geometry lives in gap_points as [[lat,lng],...] -- the same encoding as
-- project_routes.route_points, so the same readers handle both.
--
-- Run this BEFORE the generated data file supabase_leon_road_network_gaps_data.sql.
-- ============================================================

-- Barangay attribution on projects. fmr_projects had no barangay column at all:
-- the barangay was buried in free-text `location` and recovered by
-- location.split(',')[0], while priorityScoring.js read project.barangay and got
-- undefined -- which is why ranked rows printed the literal word "Barangay".
ALTER TABLE public.fmr_projects ADD COLUMN IF NOT EXISTS barangay TEXT;
ALTER TABLE public.fmr_projects ADD COLUMN IF NOT EXISTS barangay_end TEXT;
ALTER TABLE public.fmr_projects ADD COLUMN IF NOT EXISTS inventory_road_name TEXT;
-- True when project_length_km disagrees with the surveyed road length, so the
-- conflict is visible in the data instead of being silently averaged away.
ALTER TABLE public.fmr_projects ADD COLUMN IF NOT EXISTS length_conflict BOOLEAN DEFAULT FALSE;

CREATE INDEX IF NOT EXISTS idx_fmr_projects_barangay
  ON public.fmr_projects(municipality, barangay);

-- ------------------------------------------------------------
-- road_network_gaps
-- ------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.road_network_gaps (
  id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  gap_code           TEXT UNIQUE NOT NULL,          -- e.g. 'LEON-GAP-201'

  -- The project whose route this gap continues from, and the project it would
  -- connect to if closed. to_project_id NULL = an orphan gap, which is the
  -- stronger prioritization signal (nothing onward is funded).
  from_project_id    BIGINT REFERENCES public.fmr_projects(id) ON DELETE CASCADE,
  to_project_id      BIGINT REFERENCES public.fmr_projects(id) ON DELETE SET NULL,

  municipality       TEXT DEFAULT 'Leon',
  barangay           TEXT,
  barangay_end       TEXT,

  -- The SURVEYED unpaved length from Leon_barangay_roads.csv. This is the
  -- authoritative figure and the one the prioritization module scores on.
  gap_km             DOUBLE PRECISION NOT NULL CHECK (gap_km > 0),
  -- How much of that length the generator could actually draw on the road network.
  -- Usually equal to gap_km; smaller where the mapped corridor ran out. Kept
  -- separate so a drawing limitation never silently changes the ranking input.
  mapped_gap_km      DOUBLE PRECISION,
  gap_type           TEXT,                          -- Earth / Gravel / Mixed Earth-Gravel Gap
  surface_condition  TEXT,                          -- worst condition among the unpaved surfaces
  gap_reason         TEXT,

  -- Provenance. Every row must be traceable to a CSV row, so the thesis can state
  -- exactly which numbers are surveyed and which are inferred.
  gap_source         TEXT NOT NULL DEFAULT 'inventory-surface',
  source_road_name   TEXT,                          -- inventory roadName
  source_surface_summary TEXT,                      -- e.g. 'Earth 1.44 km (98%, Poor)'
  route_source       TEXT,                          -- how the alignment was obtained
  route_quality      TEXT,                          -- how trustworthy that alignment is

  start_latitude     DOUBLE PRECISION,
  start_longitude    DOUBLE PRECISION,
  end_latitude       DOUBLE PRECISION,
  end_longitude      DOUBLE PRECISION,
  gap_points         JSONB NOT NULL DEFAULT '[]'::jsonb,   -- [[lat,lng],...]

  -- Network distance from the gap's far end to Leon Public Market, for the
  -- market-access factor in the prioritization module.
  market_distance_km DOUBLE PRECISION,
  connects_to_market BOOLEAN DEFAULT FALSE,

  created_at         TIMESTAMPTZ DEFAULT now(),
  updated_at         TIMESTAMPTZ DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_road_network_gaps_from ON public.road_network_gaps(from_project_id);
CREATE INDEX IF NOT EXISTS idx_road_network_gaps_to   ON public.road_network_gaps(to_project_id);
CREATE INDEX IF NOT EXISTS idx_road_network_gaps_area ON public.road_network_gaps(municipality, barangay);

-- ------------------------------------------------------------
-- RLS: public read, authenticated write.
--
-- Deliberately NOT the pattern used by supabase_project_routes_migration.sql:37-47,
-- which grants anon INSERT/UPDATE/DELETE on route geometry -- that lets anyone
-- holding the publishable key rewrite any project's alignment.
-- ------------------------------------------------------------
ALTER TABLE public.road_network_gaps ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS road_network_gaps_select_all ON public.road_network_gaps;
CREATE POLICY road_network_gaps_select_all
  ON public.road_network_gaps FOR SELECT
  USING (true);

DROP POLICY IF EXISTS road_network_gaps_write_authenticated ON public.road_network_gaps;
CREATE POLICY road_network_gaps_write_authenticated
  ON public.road_network_gaps FOR ALL
  TO authenticated
  USING (true)
  WITH CHECK (true);

GRANT SELECT ON public.road_network_gaps TO anon;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.road_network_gaps TO authenticated;

-- ------------------------------------------------------------
-- Normalize project_routes.route_points to the [[lat,lng],...] encoding.
--
-- The column currently holds two shapes: [[lat,lng],...] from the SQL seeds and
-- [{"lat":..,"lng":..},...] from the admin route builder (Dashboard.jsx
-- upsertProjectRoute). Readers tolerate both via pointFromObject, but audit and
-- verification SQL cannot compare geometry across two encodings without
-- branching. The writer is being changed to emit arrays; this converts the rows
-- already stored as objects.
-- ------------------------------------------------------------
UPDATE public.project_routes AS r
SET route_points = converted.points,
    updated_at = now()
FROM (
  SELECT pr.id,
         COALESCE(
           jsonb_agg(
             jsonb_build_array(
               (elem -> 'lat')::double precision,
               (elem -> 'lng')::double precision
             )
             ORDER BY ord
           ),
           '[]'::jsonb
         ) AS points
  FROM public.project_routes pr
  CROSS JOIN LATERAL jsonb_array_elements(pr.route_points) WITH ORDINALITY AS t(elem, ord)
  WHERE jsonb_typeof(pr.route_points) = 'array'
    AND jsonb_array_length(pr.route_points) > 0
    -- only rows whose elements are objects carrying lat/lng
    AND jsonb_typeof(pr.route_points -> 0) = 'object'
    AND (pr.route_points -> 0) ? 'lat'
    AND (pr.route_points -> 0) ? 'lng'
  GROUP BY pr.id
) AS converted
WHERE r.id = converted.id;
