-- ============================================================
-- KalsaTrack - Real budget allocation tranche tracking
-- Replaces the client-side-only, never-persisted disbursement
-- schedule in src/lib/budgetEstimate.js with a real, auditable
-- release workflow: a DA admin initializes the 4 standard RA-9184
-- tranches once a project's total_budget is set, then explicitly
-- releases each one as physical progress clears its threshold.
-- Run this in your Supabase SQL Editor.
-- ============================================================

CREATE TABLE IF NOT EXISTS public.project_tranches (
  id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  project_id       BIGINT NOT NULL REFERENCES public.fmr_projects(id) ON DELETE CASCADE,
  tranche_order    INTEGER NOT NULL,
  tranche_name     TEXT NOT NULL,
  percentage       NUMERIC(5,2) NOT NULL,
  amount           NUMERIC NOT NULL DEFAULT 0,
  required_progress NUMERIC NOT NULL DEFAULT 0,
  status           TEXT NOT NULL DEFAULT 'Pending' CHECK (status IN ('Pending', 'Released')),
  released_amount  NUMERIC,
  released_date    DATE,
  released_by      UUID REFERENCES public.profiles(id) ON DELETE SET NULL,
  released_by_name TEXT,
  notes            TEXT,
  created_at       TIMESTAMPTZ DEFAULT now(),
  updated_at       TIMESTAMPTZ DEFAULT now(),
  UNIQUE (project_id, tranche_order)
);

ALTER TABLE public.project_tranches ENABLE ROW LEVEL SECURITY;

-- Read: everyone (matches the open-read pattern already used for
-- fmr_projects/market_locations -- LGU, contractor, field engineer, and
-- the public map/project pages all show release history read-only).
CREATE POLICY "Anyone can view project_tranches"
  ON public.project_tranches FOR SELECT TO anon, authenticated USING (true);

-- Insert/Update/Delete: admin only, and in practice only ever reached via
-- the two SECURITY DEFINER RPCs below (the app never writes this table
-- directly), which re-check the role themselves regardless of these
-- policies.
CREATE POLICY "Admins can insert project_tranches"
  ON public.project_tranches FOR INSERT TO authenticated
  WITH CHECK (public.current_profile_role() = 'admin');

CREATE POLICY "Admins can update project_tranches"
  ON public.project_tranches FOR UPDATE TO authenticated
  USING (public.current_profile_role() = 'admin')
  WITH CHECK (public.current_profile_role() = 'admin');

CREATE POLICY "Admins can delete project_tranches"
  ON public.project_tranches FOR DELETE TO authenticated
  USING (public.current_profile_role() = 'admin');

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_publication_tables
    WHERE pubname = 'supabase_realtime' AND tablename = 'project_tranches'
  ) THEN
    ALTER PUBLICATION supabase_realtime ADD TABLE public.project_tranches;
  END IF;
END $$;

-- ============================================================
-- initialize_project_tranches: seeds the 4 standard RA-9184-modeled
-- tranche rows for a project (same schedule already hardcoded as an
-- estimate in src/lib/budgetEstimate.js's TRANCHE_SCHEDULE). Idempotent:
-- re-running it for a project that already has rows is a no-op.
-- ============================================================
CREATE OR REPLACE FUNCTION public.initialize_project_tranches(p_project_id BIGINT)
RETURNS void AS $$
DECLARE
  v_total_budget NUMERIC;
BEGIN
  IF public.current_profile_role() <> 'admin' THEN
    RAISE EXCEPTION 'Only admins can initialize a project budget allocation';
  END IF;

  SELECT total_budget INTO v_total_budget
  FROM public.fmr_projects WHERE id = p_project_id;

  IF v_total_budget IS NULL OR v_total_budget <= 0 THEN
    RAISE EXCEPTION 'Project must have a total_budget set before tranches can be initialized';
  END IF;

  INSERT INTO public.project_tranches
    (project_id, tranche_order, tranche_name, percentage, amount, required_progress)
  VALUES
    (p_project_id, 1, 'Mobilization Advance', 15.00, v_total_budget * 0.15, 0),
    (p_project_id, 2, '1st Progress Release', 35.00, v_total_budget * 0.35, 30),
    (p_project_id, 3, '2nd Progress Release', 40.00, v_total_budget * 0.40, 70),
    (p_project_id, 4, 'Retention Release', 10.00, v_total_budget * 0.10, 100)
  ON CONFLICT (project_id, tranche_order) DO NOTHING;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER
   SET search_path = public
   SET row_security = off;

GRANT EXECUTE ON FUNCTION public.initialize_project_tranches(BIGINT) TO authenticated;

-- ============================================================
-- release_project_tranche: the actual approval action. Re-validates the
-- progress gate server-side (not just in the UI) so it can't be bypassed,
-- then marks the tranche Released and rolls the amount into
-- fmr_projects.funds_released so that figure stays authoritative once a
-- project has real tranches.
-- ============================================================
CREATE OR REPLACE FUNCTION public.release_project_tranche(
  p_tranche_id BIGINT,
  p_released_amount NUMERIC,
  p_released_date DATE,
  p_notes TEXT DEFAULT NULL
)
RETURNS void AS $$
DECLARE
  v_actor_name text;
  v_project_id BIGINT;
  v_required_progress NUMERIC;
  v_status TEXT;
  v_accomplishment NUMERIC;
BEGIN
  IF public.current_profile_role() <> 'admin' THEN
    RAISE EXCEPTION 'Only admins can release a tranche';
  END IF;

  SELECT full_name INTO v_actor_name FROM public.profiles WHERE id = auth.uid();

  SELECT project_id, required_progress, status
    INTO v_project_id, v_required_progress, v_status
  FROM public.project_tranches WHERE id = p_tranche_id;

  IF NOT FOUND THEN
    RAISE EXCEPTION 'Tranche not found';
  END IF;

  IF v_status <> 'Pending' THEN
    RAISE EXCEPTION 'Tranche has already been released';
  END IF;

  SELECT accomplishment INTO v_accomplishment
  FROM public.fmr_projects WHERE id = v_project_id;

  IF COALESCE(v_accomplishment, 0) < v_required_progress THEN
    RAISE EXCEPTION 'Project has not yet reached the % required progress for this tranche', v_required_progress;
  END IF;

  UPDATE public.project_tranches
  SET status = 'Released',
      released_amount = p_released_amount,
      released_date = p_released_date,
      released_by = auth.uid(),
      released_by_name = v_actor_name,
      notes = p_notes,
      updated_at = now()
  WHERE id = p_tranche_id;

  UPDATE public.fmr_projects
  SET funds_released = COALESCE(funds_released, 0) + p_released_amount,
      updated_at = now()
  WHERE id = v_project_id;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER
   SET search_path = public
   SET row_security = off;

GRANT EXECUTE ON FUNCTION public.release_project_tranche(BIGINT, NUMERIC, DATE, TEXT) TO authenticated;
