/**
 * Generate SQL to insert LGU Leon Road Inventory into Supabase
 * Run: node scripts/generate_leon_road_inventory_sql.js
 */
const fs = require('fs');
const roads = require('../src/data/leonRoadInventory.json');

let sql = `-- ============================================================
-- KalsaTrack - LGU Leon Road Inventory
-- Insert script for the lgu_road_inventory table
-- Generated from leonRoadInventory.json (${roads.length} roads)
-- ============================================================

-- 1. Create the lgu_road_inventory table (safe, additive)
CREATE TABLE IF NOT EXISTS public.lgu_road_inventory (
  id                    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  road_name             TEXT NOT NULL,
  barangay              TEXT DEFAULT '',
  municipality          TEXT DEFAULT 'Leon',
  province              TEXT DEFAULT 'Iloilo',
  classification        TEXT DEFAULT '',
  length_km             DOUBLE PRECISION DEFAULT 0,
  right_of_way_m        DOUBLE PRECISION DEFAULT 0,
  year_constructed      INTEGER,
  surface_type          TEXT DEFAULT '',
  condition             TEXT DEFAULT '',
  surface_summary       TEXT DEFAULT '',
  -- Denormalized surface breakdown columns
  concrete_km           DOUBLE PRECISION,
  concrete_pct          DOUBLE PRECISION,
  concrete_condition    TEXT,
  asphalt_km            DOUBLE PRECISION,
  asphalt_pct           DOUBLE PRECISION,
  asphalt_condition     TEXT,
  gravel_km             DOUBLE PRECISION,
  gravel_pct            DOUBLE PRECISION,
  gravel_condition      TEXT,
  earth_km              DOUBLE PRECISION,
  earth_pct             DOUBLE PRECISION,
  earth_condition       TEXT,
  source                TEXT DEFAULT 'LGU Leon Road Inventory',
  created_at            TIMESTAMPTZ DEFAULT now(),
  updated_at            TIMESTAMPTZ DEFAULT now()
);

-- 2. Enable Row Level Security
ALTER TABLE public.lgu_road_inventory ENABLE ROW LEVEL SECURITY;

-- 3. RLS Policies
CREATE POLICY IF NOT EXISTS "Anyone authenticated can view lgu_road_inventory"
  ON public.lgu_road_inventory FOR SELECT TO authenticated USING (true);

CREATE POLICY IF NOT EXISTS "Anon users can view lgu_road_inventory"
  ON public.lgu_road_inventory FOR SELECT TO anon USING (true);

CREATE POLICY IF NOT EXISTS "Authenticated users can insert lgu_road_inventory"
  ON public.lgu_road_inventory FOR INSERT TO authenticated WITH CHECK (true);

CREATE POLICY IF NOT EXISTS "Authenticated users can update lgu_road_inventory"
  ON public.lgu_road_inventory FOR UPDATE TO authenticated USING (true);

CREATE POLICY IF NOT EXISTS "Authenticated users can delete lgu_road_inventory"
  ON public.lgu_road_inventory FOR DELETE TO authenticated USING (true);

-- 4. Enable Realtime
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_publication_tables
    WHERE pubname = 'supabase_realtime' AND tablename = 'lgu_road_inventory'
  ) THEN
    ALTER PUBLICATION supabase_realtime ADD TABLE public.lgu_road_inventory;
  END IF;
END $$;

-- ============================================================
-- 5. INSERT ALL 143 ROAD RECORDS
-- ============================================================

INSERT INTO public.lgu_road_inventory (
  road_name, barangay, municipality, classification, length_km,
  right_of_way_m, year_constructed, surface_type, condition, surface_summary,
  concrete_km, concrete_pct, concrete_condition,
  asphalt_km, asphalt_pct, asphalt_condition,
  gravel_km, gravel_pct, gravel_condition,
  earth_km, earth_pct, earth_condition
) VALUES
`;

const rows = roads.map(r => {
  const getSurface = (type) => r.surfaces.find(s => s.type === type) || { length: null, pct: null, condition: null };

  const concrete = getSurface('Concrete');
  const asphalt = getSurface('Asphalt');
  const gravel = getSurface('Gravel');
  const earth = getSurface('Earth');

  const esc = (v) => {
    if (v === null || v === undefined) return 'NULL';
    if (typeof v === 'number') return v;
    // Escape single quotes by doubling them
    return `'${String(v).replace(/'/g, "''")}'`;
  };

  return `(
  ${esc(r.roadName)},
  ${esc(r.barangay)},
  'Leon',
  'Iloilo',
  ${esc(r.classification)},
  ${r.lengthKm ?? 'NULL'},
  ${r.row ?? 'NULL'},
  ${r.yearConstructed ?? 'NULL'},
  ${esc(r.surfaceType)},
  ${esc(r.condition)},
  ${esc(r.surfaceSummary)},
  ${concrete.length ?? 'NULL'}, ${concrete.pct ?? 'NULL'}, ${esc(concrete.condition)},
  ${asphalt.length ?? 'NULL'}, ${asphalt.pct ?? 'NULL'}, ${esc(asphalt.condition)},
  ${gravel.length ?? 'NULL'}, ${gravel.pct ?? 'NULL'}, ${esc(gravel.condition)},
  ${earth.length ?? 'NULL'}, ${earth.pct ?? 'NULL'}, ${esc(earth.condition)}
)`;
});

sql += rows.join(',\n') + ';\n\n';

sql += `-- ============================================================
-- Done! ${roads.length} road records inserted for LGU Leon
-- Total length: ${roads.reduce((sum, r) => sum + (r.lengthKm || 0), 0).toFixed(2)} km
-- Barangays covered: ${[...new Set(roads.map(r => r.barangay))].length}
-- ============================================================

-- Quick verification query:
-- SELECT COUNT(*) AS total_roads, ROUND(SUM(length_km)::numeric, 2) AS total_km
-- FROM public.lgu_road_inventory;
`;

fs.writeFileSync('supabase_leon_road_inventory.sql', sql, 'utf8');
console.log(`Generated supabase_leon_road_inventory.sql with ${roads.length} road records.`);